name: physik131
channels:
  - conda-forge
dependencies:
  - nodejs
  - jupyterlab
  - astropy 
  - numpy
  - pandas
  - scipy
  - matplotlib
  - sympy 
  - scikit-image 
  - scikit-learn 
  - seaborn 
  - colorama 
  - pyhdf 
  - h5py 
  - pydub
  - ipywidgets 
  - ipyevents 
  - ipympl 
  - jupyter_contrib_nbextensions
  - version_information 
  - jupyter-archive==3.3.4
  - jupyterlab-git
  - nbresuse 
  - spyder
  - jupyter-server-proxy>=1.4 
  - websockify
  - lmfit
  - numba 
  - plotly 
  - jax
  - jupyterlab-topbar
  - jupyterlab-system-monitor
  - jupyterlab-spellchecker
  - jupyter_server>2
  - corner
  - astroquery
  - pyccl
  - galsim
  - camb
  - treecorr
  - nbconvert-pandoc
  - photutils
  - ccdproc
  - astroplan
  - sbpy
  - astrometry
